### PR TITLE
Fix BeforeEachTest so that it doesn't fail sporadically

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

- Bugfix

### Description

Fix `BeforeEachTest` so that it doesn't fail sporadically.

### Additional Context

_Why are you making this pull request?_

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [x] Write tests
- [x] Make sure all tests pass
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Review by SamBarker — APPROVED** [review]
What was the underlying cause of the failure? As in why do we still have topics when the cluster is injected

**Comment by robobario** [comment]
> What was the underlying cause of the failure? As in why do we still have topics when the cluster is injected

It's attempting to test that a topic created in the `BeforeEach` is available later in the test case (proving we are able to manipulate the same cluster from the `BeforeEach`. At a guess there must be some eventual consistency in there where the success of the topic creation doesn't guarantee it's available for listing. Maybe success means it was successfully written to the KRaft log but it's not been consumed back out yet.

**Review by robobario — APPROVED** [review]
LGTM

**Comment by SamBarker** [comment]
> It's attempting to test that a topic created in the `BeforeEach` is available later in the test case (proving we are able to manipulate the same cluster from the `BeforeEach`. At a guess there must be some eventual consistency in there where the success of the topic creation doesn't guarantee it's available for listing. Maybe success means it was successfully written to the KRaft log but it's not been consumed back out yet.

Yeah `createTopic` returning just means the broker has the request not that the topic is available. See [Utils.awaitExpectedBrokerCountInClusterViaTopic](https://github.com/kroxylicious/kroxylicious-junit5-extension/blob/12ee8a724451dbff65fbe1d18492cc1de704fe47/impl/src/main/java/io/kroxylicious/testing/kafka/common/Utils.java#L124-L125)

**Pull request merged**
