### PR TITLE
Upgrade to kafka-clients 3.5.0

### PR DESCRIPTION
**Pull request by robobario**
### Type of change

- Enhancement / new feature

### Description

Upgrade to kafka-clients 3.5.0

### Additional Context

kafka-clients 3.5.0 has some breaking changes so when we upgraded
it in kroxylicious the embedded kafka broker couldn't start. The
3.4.0 broker code is attempting to call methods removed in
kafka-clients 3.5.0

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [x] Make sure all tests pass
- [ ] Update documentation
- [x] Reference relevant issue(s) and close them after merging
- [x] Update CHANGELOG.md

### CODE REVIEW

**Review by SamBarker — APPROVED** [review]
LGTM

Thanks @robobario

**Comment by robobario** [comment]
Bit of a bother that the next version of the extension will only be compatible with the latest kafka-clients lib

**Comment by robobario** [comment]
Alright, I pushed up a change to reflectively instantiate the KafkaRaftServer, with a fallback to the old constructor. This enables users to downgrade kafka_2.13 if they need/want to run with an older kafka-clients lib. Tested against kroxylicious by adding a test scoped dependency on `kafka_2.13:3.4.0` to downgrade.

**Review by k-wall — APPROVED** [review]

**Comment by k-wall** [comment]
thanks @robobario

**Comment by showuon** [comment]
Looks good to use the reflection for backward compatibility! Sorry for late review!

**Pull request merged**
