### PR TITLE
Allow TemplateTest methods to be run individually

### PR DESCRIPTION
**Pull request by k-wall**
Fix a couple of logging levels too.

### CODE REVIEW

**Review by SamBarker — COMMENTED** [review]
This is largely my ignorance but why does making the shared state fields `AtomicReferences` achieve the goal from the PR title.

**Comment by franvila** [comment]
Me too, it is the first time I see `AtomicReference` as well and don't know how it works at all.

**Review by franvila — COMMENTED** [review]
Me too, it is the first time I see `AtomicReference` as well and don't know how it works at all.

**Comment by k-wall** [comment]
Problem I am trying to solve: It is bothersome that we cannot run a test individually -Dtest=TemplateTest#testTuples without seeing a whole bunch of spurious test failures corresponding to tests that haven't run.

Maybe the ARs were distateful/magic.  I was relying on the compare and swap setting the AR once if the test actually ran and making the afterall execution check that it had (with an assumeTrue).

So I had another go at achieving the same ends.   Now I'm using Nested tests which means you can runs the tests in the IDE, or from the command line.

```
mvn verify -Dmaven.javadoc.skip=true '-Dtest=TemplateTest$Tuples#testTuples'
```

Alternatively, using a separate file per test case is an option, but that would mean moving the static methods into their own file `clusterSizes` etc is shared.    I don't like that as that would separate the test data from its assertion,.

**Review by SamBarker — APPROVED** [review]
LGTM I had played with a similar change but didn't twig the idea of having the nested class implement `AfterAllCallback`

**Comment by franvila** [comment]
LGTM. Thanks @k-wall !

**Pull request merged**
